all_cars = [{"brand": "Opel", "Model": "Astra H", "hp": 150, "price": 2500},
            {"brand": "Dacia", "Model": "Logan I", "hp": 100, "price": 900},
            {"brand": "Bmw", "Model": "520d", "hp": 190, "price": 15000},
            {"brand": "Ford", "Model": "Focus II", "hp": 130, "price": 2000},
            {"brand": "Dacia", "Model": "Sandero", "hp": 90, "price": 700},
            {"brand": "Volkswagen", "Model": "Passat", "hp": 170, "price": 5000},
            {"brand": "Skoda", "Model": "Superb", "hp": 150, "price": 4000},
            {"brand": "Audi", "Model": "A6", "hp": 190, "price": 13000},
            {"brand": "Mercedes-Benz", "Model": "E-klasse", "hp": 190, "price": 17000},
            {"brand": "Skoda", "Model": "Octavia", "hp": 140, "price": 3000}]